config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'patients#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :nurse_tasks, only: [:index, :update] do
    collection do
      patch :sort, :complete
    end
  end
  patch 'nurse_tasks/make_active/:id', to: "nurse_tasks#make_active", as: "make_active_nurse_task"
  resources :patients, only: [:index, :show]
  get 'patient_assignment', to: 'patients#patient_assignment'
  post 'create_patient_assignment', to: 'patients#create_patient_assignment'
  post 'update_patient_assignment', to: 'patients#create_patient_assignment'

  resources :users, path: :nurses, only: [:index, :show]
  post 'help', to: 'users#help'

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  belongs_to :leader, required: false, class_name: 'User'
  has_many :nurses, class_name: 'User', foreign_key: 'leader_id'
  validates :name, presence: true
  validates :email, uniqueness: true
  has_many :nurse_tasks, dependent: :destroy
  has_many :task_templates, through: :nurse_tasks
  has_many :patients, through: :task_templates
  has_many :notifications, foreign_key: :recipient_id

  has_one_attached :photo
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @nurses = current_user.nurses.includes(:patients, :nurse_tasks)
    @task_count_all = @nurses.sum { |nurse| nurse.nurse_tasks.count }
    task_count_complete = @nurses.sum { |nurse| nurse.nurse_tasks.where(completed: true).count }
    @task_completed_decimal = task_count_complete.to_f / @task_count_all
    @patients = @nurses.map do |nurse|
      Patient.joins(:task_templates).joins(task_templates: :nurse_tasks)
             .where(task_templates: { nurse_tasks: { user: nurse } }).uniq
    end.flatten

    high_care_patients = 0
    medium_care_patients = 0
    low_care_patients = 0
    @patients.each do |patient|
      case patient.severity
      when 'High Care' then high_care_patients += 1
      when 'Medium Care' then medium_care_patients += 1
      when 'Low Care' then low_care_patients += 1
      end
    end

    @high_care_patients = high_care_patients
    @medium_care_patients = medium_care_patients
    @low_care_patients = low_care_patients
  end

  def show
    @user = User.find(params[:id])
    @active_task = @user.nurse_tasks.find_by(active: true)
    if @active_task.nil?
      @active_task = @user.nurse_tasks.where(slot: 8).first
      @active_task.active = true
      @active_task.save
    end
    @patients = @user.patients.uniq
    @high_care_patients = @user.patients.where(severity: 'High Care').uniq.count
    @medium_care_patients = @user.patients.where(severity: 'Medium Care').uniq.count
    @low_care_patients = @user.patients.where(severity: 'Low Care').uniq.count
  end

  def help
    new_help = Help.new
    new_help.save
    Notification.create(recipient: current_user.leader, actor: current_user, action: "requested", notifiable: new_help)
    redirect_to request.referrer
  end
end

app/views/users/index.html.erb
<%= render 'shared/banner', user: current_user, patients: @patients.uniq, nurses: false, task_count_all: @task_count_all, task_completed_decimal: @task_completed_decimal %>
<div class="main-container">
  <div class="grip">
    <div class="justify-content-around text-center m-3">
      <% unless  current_user.on_shift%>
      <%= form_tag(create_patient_assignment_path, remote: true) do %>
      <%= submit_tag "Start the shift", class: "btn btn-primary btn-lg w-25"%>
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="leader-cards">
    <% @nurses.each_with_index do |nurse| %>
    <div class="grid-item">
      <%= link_to user_path(nurse), class: "leader-card shadow" do %>


      <% if false %>
        <% incomplete_morning_tasks_min = nurse.nurse_tasks.where(slot: 8, completed: false).map{|nurse_task| nurse_task.task_template.task.duration}.reduce(:+) || 0 %>
        <% incomplete_afternoon_tasks_min = nurse.nurse_tasks.where(slot: 12, completed: false).map{|nurse_task| nurse_task.task_template.task.duration}.reduce(:+) || 0 %>
        <div class="row">
          <div class="col-9">
            <p class="late-time mb-0">
              <% unless incomplete_morning_tasks_min == 0 %>
              <% total_min = incomplete_morning_tasks_min + incomplete_afternoon_tasks_min + 60 %>
              <% else %>
              <% total_min = incomplete_afternoon_tasks_min %>
              <% end %>
              <% delay = (Time.parse("17:00") - (Time.now + (total_min * 60))).round / -60  %>
              <% unless nurse.nurse_tasks.size == 0 || delay < 0 %>
                <%= delay %> mins late
              <% end %>
            </p>
          </div>
          <div class="col-3">
            <% if (Time.now + (total_min * 60)) > Time.parse("17:30") %>
              <div class="d-flex">
                <i class="fas fa-stopwatch very-late"></i>
              </div>
              <% elsif (Time.now + (total_min * 60)) > Time.parse("17:00") %>
              <div class="d-flex">
                <i class="fas fa-stopwatch"></i>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>


      <h5 class="pt-3"><%= nurse.name %></h5>
      <% if nurse.photo.attached? %>
      <%= cl_image_tag nurse.photo.key, class: "avatar-super-large pb-3" %>
      <% else %>
      <%= image_tag "avatar.png", class: "avatar-super-large pb-3" %>
      <% end %>
      <div class="row justify-content-center">
         <!-- This is where the element for the progress bar is found with the dataset to draw the circle -->
        <div id="task-progress" data-id="<%= nurse.id %>" data-tasks="<%= ((nurse.nurse_tasks.where(completed: true).count.to_f / nurse.nurse_tasks.count))%>"></div>
      </div>
      <div class="mt-2 text-center">
        <% patient_severitys = Patient.joins(:task_templates).joins(task_templates: :nurse_tasks).where(task_templates: { nurse_tasks: { user: nurse } }).pluck(:name, :severity).uniq%>
      </div>
      <% if patient_severitys.count > 0 %>
      <ul class="assignment-list mt-0">
        <% priority = {'Low Care' => 3, 'Medium Care' => 2, 'High Care' => 1} %>
        <% patient_severitys.sort_by { |ps| priority[ps[1]] }.each do |patient_severity| %>
        <li class="text-left <%= patient_severity[1].downcase.tr(" ", "-") %> " style="font-size: 12px;">・<%= patient_severity[0] %></li>
        <% end %>
      </ul>
      <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'shared/banner', user: current_user, patients: @patients, nurses: [@user]  %>
<div class="main-container">
  <div class="container-fluid">
    <div class="row">
      <div class="col-8  offset-2 nurse-details">
        <div class="row px-3 pt-3">
          <div class="col-4 text-center">
            <h2><%= @user.name %></h2>
          </div>
          <div class="col-8 text-center">
            <div class="row">
              <div class="col-10">
                <h2>Current Task</h2>
              </div>
              <div class="col-2">
                <div class="row">
                  <% if @active_task.task_template.patient.severity == 'Low Care' %>
                  <div class="patient-room-info p-1 low-care text-center col">
                    <p class="mb-0"><small>Low</small></p>
                    <% elsif @active_task.task_template.patient.severity == 'Medium Care' %>
                    <div class="patient-room-info p-1 medium-care text-center col">
                      <p class="mb-0"><small>Medium</small></p>
                      <% elsif @active_task.task_template.patient.severity == 'High Care' %>
                      <div class="patient-room-info p-1 high-care text-center col">
                        <p class="mb-0"><small>High</small></p>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>
            <div class="row px-3 pt-2 pb-3">
              <div class="nurse-info col-4 text-center">
                <% if @user.photo.attached? %>
                <%= cl_image_tag @user.photo.key, class: "avatar-mega-large" %>
                <% else %>
                <%= image_tag "avatar.png", class: "avatar-mega-large" %>
                <% end %>
              </div>
              <div class="patient-details col-8">
                <div class="row pt-3">
                  <div class="patient-info col-10 d-flex justify-content-center">
                    <h4 class="pr-3"><%= @active_task.task_template.patient.name %></h4>
                    <h4 class="pr-3"><i class="fas fa-door-closed"></i> <%= @active_task.task_template.patient.room %></h4>
                    <h4><i class="fa fa-bed" aria-hidden="true"></i> <%= @active_task.task_template.patient.bed %></h4>
                  </div>
                </div>
                <div class="row">
                  <div class="task-info col-10 pt-3 d-flex justify-content-center">
                    <h4 class="pr-3"><%= @active_task.task_template.task.description %></h4>
                    <h4><%= @active_task.task_template.task.duration %> mins</h4>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row pt-3">
          <%= render 'shared/patient_cards', patients: @patients %>
        </div>
      </div>
    </div>