config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'patients#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :nurse_tasks, only: [:index, :update] do
    collection do
      patch :sort, :complete
    end
  end
  patch 'nurse_tasks/make_active/:id', to: "nurse_tasks#make_active", as: "make_active_nurse_task"
  resources :patients, only: [:index, :show]
  get 'patient_assignment', to: 'patients#patient_assignment'
  post 'create_patient_assignment', to: 'patients#create_patient_assignment'
  post 'update_patient_assignment', to: 'patients#create_patient_assignment'

  resources :users, path: :nurses, only: [:index, :show]
  post 'help', to: 'users#help'

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end
end

app/models/nurse_task.rb
class NurseTask < ApplicationRecord
  SLOTS = [0, 4, 8, 12, 16, 20]
  belongs_to :user
  belongs_to :helper, required: false, class_name: 'User'
  belongs_to :task_template
  validates :task_template, :user, presence: true
  validates :slot, presence: true, inclusion: { in: SLOTS }
end

app/controllers/nurse_tasks_controller.rb
class NurseTasksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    set_index_variables!
    @patients = current_user.patients.uniq
    @high_care_patients = current_user.patients.where(severity: 'High Care').uniq.count
    @medium_care_patients = current_user.patients.where(severity: 'Medium Care').uniq.count
    @low_care_patients = current_user.patients.where(severity: 'Low Care').uniq.count
  end

  def sort
    # Start time should be 8AM + duration of completed tasks (for example)
    start_time = Time.parse("8:00")
    params[:nurse_tasks_morning].each_with_index do |id, index|
      current_task = NurseTask.find(id)
      current_task.update(slot: 8, position: index + 1, start_time: start_time)
      start_time = start_time + (current_task.task_template.task.duration * 60)
    end
    # consider 1 hour lunch break
    start_time = start_time + (60 * 60)
    params[:nurse_tasks_afternoon].each_with_index do |id, index|
      current_task = NurseTask.find(id)
      current_task.update(slot: 12, position: index + 1, start_time: start_time)
      start_time = start_time + (current_task.task_template.task.duration * 60)
    end

    set_index_variables!
  end

  def complete
    @nurse_task = NurseTask.find(params[:format])
    @nurse_task.completed = true
    @nurse_task.active = false
    @nurse_task.save
    new_active_task =
      NurseTask.where(user: current_user, slot: 8, completed: false).order(:position)[0] ||
      NurseTask.where(user: current_user, slot: 12, completed: false).order(:position)[0]
    new_active_task.active = true
    new_active_task.save
    redirect_to nurse_tasks_path
  end

  def make_active
    previous_task = NurseTask.where(user: current_user, active: true)[0]
    unless previous_task.nil?
      previous_task.active = false
      previous_task.save
    end
    @nurse_task = NurseTask.find(params[:id])
    @nurse_task.active = true
    @nurse_task.save
    redirect_to nurse_tasks_path
  end

  def update
    nurse_task = NurseTask.find(params[:id])
    nurse_task.update(nurse_task_params)
    redirect_to nurse_tasks_path
  end

  private

  def nurse_task_params
    params.require(:nurse_task).permit(:note)
  end

  def set_index_variables!
    @nurse_tasks = NurseTask.where(user: current_user)
    if @nurse_tasks.first.position
      @nurse_tasks = @nurse_tasks.order(:position)
    else
      @nurse_tasks = @nurse_tasks.order(:id)
    end
    @active_task = NurseTask.where(user: current_user, active: true)[0]
    if @active_task.nil?
      @active_task = @nurse_tasks.where(slot: 8).first
      @active_task.active = true
      @active_task.save
    end
    @incomplete_morning_tasks = @nurse_tasks.where(slot: 8, completed: false)
    @incomplete_afternoon_tasks = @nurse_tasks.where(slot: 12, completed: false)
    @completed_morning_tasks = @nurse_tasks.where(slot: 8, completed: true)
    @completed_afternoon_tasks = @nurse_tasks.where(slot: 12, completed: true)
  end
end

app/views/nurse_tasks/index.html.erb
<%= render 'shared/highlighted_nurse_task_card', patient: @active_task.task_template.patient, nurse_task: @active_task, patients: @patients, high_care: @high_care_patients, medium_care: @medium_care_patients, low_care: @low_care_patients %>
<div class="main-container mt-0">
  <ul class="nav nav-pills mb-3 mt-3 d-flex justify-content-center" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">To do</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Completed</a>
    </li>
  </ul>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="row nurse-task-cards mt-3">
        <div class="col-6">
          <p id="nurse-tasks-morning-title"><%= render 'shared/nurse_tasks_title', time: "Morning", incomplete_tasks: @incomplete_morning_tasks %></p>
          <div id="nurse-tasks-morning" class="nurse-tasks" data-url="<%= sort_nurse_tasks_path(format: :js) %>">
            <%= render 'shared/nurse_task_cards', nurse_tasks: @incomplete_morning_tasks %>
          </div>
          </div>
        <div class="col-6">
          <p id="nurse-tasks-afternoon-title"><%= render 'shared/nurse_tasks_title', time: "Afternoon", incomplete_tasks: @incomplete_afternoon_tasks %></p>
          <div id="nurse-tasks-afternoon" class="nurse-tasks" data-url="<%= sort_nurse_tasks_path(format: :js) %>">
            <%= render 'shared/nurse_task_cards', nurse_tasks: @incomplete_afternoon_tasks %>
          </div>
        </div>
      </div>
    </div>
      <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <div class="row nurse-task-cards" id="completedTasks">
        <div class="col-6">
        <p>Morning</p>
          <div data-url="<%= sort_nurse_tasks_path(format: :js) %>">
            <%= render 'shared/nurse_task_cards', nurse_tasks: @completed_morning_tasks %>
          </div>
        </div>
        <div class="col-6">
          <p>Afternoon</p>
          <div data-url="<%= sort_nurse_tasks_path(format: :js) %>">
            <%= render 'shared/nurse_task_cards', nurse_tasks: @completed_afternoon_tasks %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/nurse_tasks/sort.js.erb
document.getElementById("nurse-tasks-morning-title").innerHTML = "<%= j(render 'shared/nurse_tasks_title', time: "Morning", incomplete_tasks: @incomplete_morning_tasks) %>";
document.getElementById("nurse-tasks-morning").innerHTML = "<%= j(render 'shared/nurse_task_cards', nurse_tasks: @incomplete_morning_tasks) %>";
document.getElementById("nurse-tasks-afternoon-title").innerHTML = "<%= j(render 'shared/nurse_tasks_title', time: "Afternoon", incomplete_tasks: @incomplete_afternoon_tasks) %>";
document.getElementById("nurse-tasks-afternoon").innerHTML = "<%= j(render 'shared/nurse_task_cards', nurse_tasks: @incomplete_afternoon_tasks) %>";