config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'patients#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :nurse_tasks, only: [:index, :update] do
    collection do
      patch :sort, :complete
    end
  end
  patch 'nurse_tasks/make_active/:id', to: "nurse_tasks#make_active", as: "make_active_nurse_task"
  resources :patients, only: [:index, :show]
  get 'patient_assignment', to: 'patients#patient_assignment'
  post 'create_patient_assignment', to: 'patients#create_patient_assignment'
  post 'update_patient_assignment', to: 'patients#create_patient_assignment'

  resources :users, path: :nurses, only: [:index, :show]
  post 'help', to: 'users#help'

  resources :notifications do
    collection do
      patch :mark_as_read
    end
  end
end

app/views/shared/_banner.html.erb
<div class="container-fluid mt-5 mb-n5">
  <div class="patient-overview mt-5 pt-5 shadow row">
    <div class="col">
      <% if user.nurses.size > 0 && action_name == 'show' %>
        <div class="col text-center">
          <h2> Here's a quick look at <%= User.find(params[:id]).name %>'s day!</h2>
        </div>
      <% else %>
        <div class="col text-center">
          <h2> Hi <%= user.name %>, here's a quick look at your day!</h2>
        </div>
      <% end %>
      <div class="col d-flex justify-content-center">
        <% if nurses %>
          <% nurses.each do |nurse| %>
            <div class=" text-center nurse-tasks-uncompleted p-3 mx-3 mb-3 shadow">
              <h5>Tasks: <%= nurse.nurse_tasks.count %></h5>
              <div class="row justify-content-center">
                <!-- This is where the progress bar element is found and then drawn -->
                <div id="task-progress" data-id="<%= nurse.id %>" data-tasks="<%= ((nurse.nurse_tasks.where(completed: true).count.to_f / nurse.nurse_tasks.count))%>"></div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class=" text-center nurse-tasks-uncompleted p-3 mx-3 mb-3 shadow">
            <h5>Tasks: <%= task_count_all %></h5>
            <div class="row justify-content-center">
              <!-- This is where the progress bar element is found and then drawn -->
              <div id="task-progress" data-tasks="<%= task_completed_decimal %>"></div>
            </div>
          </div>
        <% end %>
        <div class=" offset-1 text-center nurse-patient-info p-3 mx-3 mb-3 shadow">
          <h5>Patients: <%= patients.count %></h5>
          <div class="nurse-patient-severity d-flex">
            <!-- This tag builds the chartkick pie chart and allows custom data inputs with styling -->
            <%= pie_chart [["High Care", @high_care_patients], ["Medium Care", @medium_care_patients], ["Low Care", @low_care_patients]], height: "80px", colors: ["#DC8478", "#ecc06c", "#b8cab8"], legend: false %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Your patient care secured with <i class="fas fa-heart"></i> Medi+Safe
  </div>
</div>

app/views/shared/_highlighted_nurse_task_card.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-4">
      <div class="highlighted-task shadow">
        <div class="row pt-5">
          <div class="col text-center pb-3">
            <h2> Today's outlook:</h2>
          </div>
        </div>
        <div class="row pt-5 justify-content-center">
          <div class="col-5">
            <div class=" text-center nurse-tasks-uncompleted p-3 mb-3 shadow">
              <h5>Tasks: <%= current_user.nurse_tasks.count %></h5>
              <div class="row justify-content-center">
                <!-- This is where the progress bar element is found and then drawn -->
                <div id="task-progress" data-tasks="<%= ((current_user.nurse_tasks.where(completed: true).count.to_f / current_user.nurse_tasks.count)) %>"></div>
              </div>
            </div>
          </div>
          <div class="col-5">
            <div class="text-center nurse-patient-info p-3 mb-3 shadow">
              <h5>Patients: <%= patients.count %></h5>
              <div class="nurse-patient-severity d-flex">
                <!-- This tag builds the chartkick pie chart and allows custom data inputs with styling -->
                <%= pie_chart [["High Care", high_care], ["Medium Care", medium_care], ["Low Care", low_care]], height: "80px", colors: ["#DC8478", "#ecc06c", "#b8cab8"], legend: false %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class=" col-8">
      <div class='highlighted-task-actual shadow'>
        <div class="current-task-card row">
          <div class="col py-4 px-3">
            <div class="row">
              <div class="nurse-task-info-room pt-5 offset-1 col-5">
                <div class="nurse-task-patient pt-4 row">
                  <%= link_to patient_path(patient), class: "nurse-task-patient-name col-9" do %>
                    <h2><%= patient.name %></h2>
                  <% end %>
                  <div class="col-3">
                    <div class="row">
                      <% if @active_task.task_template.patient.severity == 'Low Care' %>
                      <div class="patient-room-info low-care text-center col">
                        <p class="mb-0"><small>Low</small></p>
                      </div>
                      <% elsif @active_task.task_template.patient.severity == 'Medium Care' %>
                        <div class="patient-room-info medium-care text-center col">
                          <p class="mb-0"><small>Medium</small></p>
                        </div>
                      <% elsif @active_task.task_template.patient.severity == 'High Care' %>
                        <div class="patient-room-info high-care text-center col">
                          <p class="mb-0"><small>High</small></p>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="row pt-3">
                  <div class="col d-flex">
                    <h5 class="pr-3"><i class="fas fa-door-closed"></i> <%= patient.room %></h5>
                    <h5><i class="fa fa-bed" aria-hidden="true"></i> <%= patient.bed %></h5>
                  </div>
                </div>
                <div class="row pt-3">
                  <div class="col d-flex">
                    <div class="nurse-task-info-description pr-3">
                      <h1><%= nurse_task.task_template.task.description %> (<%= nurse_task.task_template.task.duration %> mins)</h1>
                    </div>
                  </div>
                </div>
              </div>
              <div class="pr-0 pt-3 offset-1 col-4">
                <div class="row">
                  <div class="col">
                    <%= simple_form_for nurse_task do |f| %>
                      <%= f.input :note, label: false, input_html: {rows: 6} %>
                      <%= f.button :submit, "Update note", class: 'my-update-button shadow w-100' %>
                    <% end %>
                  </div>
                </div>
                <div class="row">
                  <div class="col p-3 text-center">
                    <div class="row pt-3">
                      <div class="col">
                        <% if nurse_task.completed == false %>
                          <div class="my-complete-button" data-toggle="modal" data-target="#exampleModal<%= nurse_task.id %>">
                            Complete
                          </div>
                        <% end %>
                      </div>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal<%= nurse_task.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Complete task</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            Are you sure you want to complete this task?
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <%= link_to "Complete", complete_nurse_tasks_path(nurse_task), method: :patch, class: 'complete-btn btn btn-primary' %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm fixed-top navbar-lewagon">
  <%= link_to '#', class: "navbar-brand" do %>
    <h2 class="mb-0"><%= image_tag "logo.png", class: "pb-2" %> MEDI+SAFE</h2>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if current_user.nurses.count > 1 %>
           <li class="nav-item">
            <%= link_to "Nurses", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown" data-behavior="notifications">
            <a class="nav-link" href="#" id="nurseLeadDropdown" role="button" data-behavior="notifications-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-bell mr-3" data-behavior="notification-bell" aria-hidden="true"></i>
              <span data-behavior="unread-count"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="nurseLeadDropdown" data-behavior="notification-items">
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Patients", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Tasks", nurse_tasks_path, class: "nav-link"  %>
          </li>
          <li class="nav-item dropdown" data-behavior="notifications">
            <a class="nav-link" href="#" id="nurseDropdown" role="button" data-behavior="notifications-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-bell mr-3" data-behavior="notification-bell" aria-hidden="true"></i>
              <span data-behavior="unread-count"></span>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="nurseDropdown" data-behavior="notification-items">
            </div>
          </li>
        <% end %>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
              <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      <% else %>
        <li class="nav-item">
          <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign in", user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_nurse_assist.html.erb
<!-- Button trigger modal -->
<div class="row justify-content-end">
<button id="assistence" type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
  <i class="fas fa-hand-holding-medical"></i>
</button>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><i class="fas fa-hand-holding-medical"></i> Assistance</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you asking for assistance?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No, thanks!</button>
        <%= link_to "Yes, please!", help_path, method: :post, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nurse_task_card.html.erb
<div class="row" data-id="<%= nurse_task.id%>" data-slot="<%= nurse_task.slot%>" data-position="<%= nurse_task.position%>">
  <div class="col-2"> <%= nurse_task.start_time.strftime("%k:%M") if nurse_task.start_time %> </div>
  <%= link_to make_active_nurse_task_path(nurse_task),
    method: "patch",
    class: "list-group nurse-task-cards col-10 row" do %>
    <div class="list-group-item align-items-center nurse-task-card <%= "active" if nurse_task.active %>">
      <div class="nurse-task-patient-name col-3 px-0">
        <%= patient.name %>
      </div>
      <div class="nurse-task-patient-info col-3 px-0">
        <p class="mb-0"><i class="fas fa-door-closed"></i> <%= patient.room %>
        <i class="fa fa-bed" aria-hidden="true"></i> <%= patient.bed %></p>
      </div>
      <div class="nurse-task-info-description col-4 px-0">
        <% important_tasks = ["Family conference",
                              "Operation",
                              "Catheter",
                              "Chemotherapy",
                              "Endoscopy",
                              "Colonoscopy"] %>
        <% current_task = nurse_task.task_template.task.description %>
        <%= current_task %>
        <% if  important_tasks.include? current_task %>
          <i class="fas fa-exclamation"></i>
        <% end %>
      </div>
      <div class="nurse-task-info-duration col-2 px-0">
        <%= nurse_task.task_template.task.duration %> mins
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_nurse_task_cards.html.erb
<% nurse_tasks.each do |nurse_task| %>
  <%= render 'shared/nurse_task_card', patient: nurse_task.task_template.patient, nurse_task: nurse_task %>
<% end %>

app/views/shared/_nurse_tasks_title.html.erb
<%= time %> - Time needed: <%= incomplete_tasks.map{|nurse_task| nurse_task.task_template.task.duration}.reduce(:+) || 0 %> min

app/views/shared/_patient_cards.html.erb
<div class="patient-cards">
  <% patients.sort_by{ |patient| patient.priority }.each do |patient| %>
    <%= link_to patient_path(patient), class: 'patient-card p-1 col shadow m-1' do %>
      <div class="overlay p-2">
        <div class="patient-info col">
          <div class="patient-info-header">
            <div class="row">
              <div class="col-4 d-flex justify-content-center">
                <h5 class="pl-2 text-center"><i class="fas fa-door-closed"></i> <%= patient.room %></h5>
                <h5 class="pl-2 text-center"><i class="fa fa-bed" aria-hidden="true"></i> <%= patient.bed %></h5>
              </div>
              <div class=" offset-4 col-4">
                <div class="row px-2">
                  <% if patient.severity == 'Low Care' %>
                    <div class="patient-room-info p-1 low-care text-center col">
                      <p>Low</p>
                  <% elsif patient.severity == 'Medium Care' %>
                    <div class="patient-room-info p-1 medium-care text-center col">
                      <p>Medium</p>
                  <% elsif patient.severity == 'High Care' %>
                    <div class="patient-room-info p-1 high-care text-center col">
                      <p>High</p>
                  <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="row justify-conten-between">
              <div class="col text-center">
                <h4><%= patient.name %></h4>
              </div>
            </div>
          </div>

          <div class="patient-info-body">
            <div class="row justify-content-center">
              <div id="task-progress" data-tasks="<%= ((patient.nurse_tasks.where(completed: true).count.to_f / patient.nurse_tasks.count))%>"></div>
            </div>
            <div class="row justify-content-center">
              <p class="col-12 text-center mb-1 pt-3"><i class="fa fa-user-md" aria-hidden="true"></i><small> Dr. <%= patient.doctor.name %></small></p>
              <p class="col-12 text-center"><i class="fa fa-mobile" aria-hidden="true"></i><small> <%= patient.doctor.contact %></small> </p>
            </div>
        </div>
        </div>

      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_task_cards.html.erb
<div class="task-card row shadow" data-id=<%= nurse_task.id %> data-slot=<%= nurse_task.slot %> data-position=<%= nurse_task.position %>>
  <div class="task-patient-info">
    <h5><%= patient.name %></h5>
    <h5 class="pt-1 pl-2"><i class="fas fa-door-closed"></i> <small><%= patient.room %></small></i></h5>
    <h5 class="pl-2"><i class="fa fa-bed" aria-hidden="true"> <small><%= patient.bed %></small></i></h5>
  </div>
  <div class="task-info d-flex">
    <div class="task-info-description col-8 px-1">
      <p><%= nurse_task.task_template.task.description %></p>
    </div>
    <div class="task-info-duration col-4 px-1">
      <p><%= nurse_task.task_template.task.duration %> mins</p>
      <% if nurse_task.completed == false %>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal<%= nurse_task.id %>">
          Complete
        </button>
      <% end %>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal<%= nurse_task.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Complete task</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to complete this task?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= link_to "Complete", complete_nurse_tasks_path(nurse_task), method: :patch, class: 'complete-btn btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>